version: '3.7'

services:
  system-data:
    image: mariadb:10.3
    user: 3000:3000
    container_name: system-data
    volumes:
      - /data/sys/system-data/data:/var/lib/mysql
      - /data/sys/system-data/config:/etc/mysql
    environment:
      MARIADB_ROOT_PASSWORD: mypass
    expose:
      - 3306
    networks:
      - master
  database:
    image: mariadb:10.3
    user: 3000:3000
    container_name: database
    volumes:
      - /data/sys/datacenter/data:/var/lib/mysql
      - /data/sys/datacenter/config:/etc/mysql
    environment:
      MARIADB_ROOT_PASSWORD: mypass
    expose:
      - 3306
    networks:
      - master
  homepage:
    image: homepage
    build:
      context: ./home
    container_name: homepage
    volumes:
      - /data/source/home/out:/data
    expose:
      - 80
    networks:
      - master
  sc-home:
    image: sc-home
    build:
      context: ./sc-home
    container_name: sc-home
    volumes:
      - /data/source/sc-home:/data
    expose:
      - 80
    networks:
      - master
  user-token-store:
    image: redis:6.2-alpine
    container_name: user-token-store
    volumes:
      - /data/sys/user-token-store/data:/data
    expose:
      - 6379
    networks:
      - master
  debug:
    image: redis:6.2-alpine
    container_name: debug
    volumes:
      - /data/sys/debug/data:/data
    expose:
      - 6379
    networks:
      - master
  proxy:
    image: proxy
    build:
      context: ./proxy
    container_name: proxy
    volumes:
      - /data/sys/proxy/conf:/etc/nginx/conf.d
      - /data/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - master
      - gitea
      - registry
  auth:
    image: auth
    build:
      context: ./auth
    container_name: auth
    volumes:
      - /data/etc/libauth.js:/etc/libauth.js
    expose:
      - 80
    networks:
      - master
  lib:
    image: lib
    build:
      context: ./lib
    container_name: lib
    expose:
      - 80
    networks:
      - master
  app:
    image: app
    build:
      context: ./var/www
    container_name: app
    expose:
      - 80
    networks:
      - master
  base-module:
    image: base-module
    build:
      context: ./var/base
    container_name: base-module
    volumes:
      - /data/etc/uniclient:/etc/uniclient
    expose:
      - 80
    networks:
      - master
networks:
  master:
    name: master
  gitea:
    external:
      name: git_gitea 
  registry:
    external:
      name: registry_registry-net
