#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

ROOT=$DIR/../..


if [ ! -d $ROOT/var/www/node_modules ]; then
	mkdir $ROOT/var/www/node_modules;
    cd $ROOT/etc;
	ln -s ../var/www/node_modules ./node_modules;
fi


cd $ROOT/var/www;

npm install --legacy-peer-deps;

chown -R $(logname) $ROOT/var/www/node_modules;
chown -R $(logname) $ROOT/lib/node_modules;
