#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

ROOT=$DIR/../..

cd $ROOT/var/www;
if [ -d ./node_modules ];then
  rm -rf ./node_modules;
fi
npm install --legacy-peer-deps;
ln -s ../../local/lib/node_modules ./node_modules;

chown -R $(logname) $ROOT/var/www/node_modules;
chown -R $(logname) $ROOT/lib/node_modules;
