#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

ROOT=$DIR/../..
DATADIR=/var/lib/uniclient
LOGDIR=/var/log/uniclient
LOCKDIR=/var/lock/uniclient
GRP=uniclient
USR=uniclient

if [ ! -d "$DATADIR" ];then

mkdir $DATADIR;
chgrp $GRP $DATADIR;
chmod 770 $DATADIR; 
echo "created $DATADIR";

else
echo "not initializing $DATADIR: DIR EXISTS!";
fi

if [ ! -d "$LOGDIR" ];then

mkdir $LOGDIR;
chgrp $GRP $LOGDIR;
chmod 770 $LOGDIR; 
echo "created $LOGDIR";

else
echo "not initializing $LOGDIR: DIR EXISTS!";
fi

if [ ! -d "$LOCKDIR" ];then

mkdir $LOCKDIR;
chgrp $GRP $LOCKDIR;
chmod 770 $LOCKDIR; 
echo "created $LOCKDIR";

else
echo "not initializing $LOCKDIR: DIR EXISTS!";
fi
