#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

ROOT=$DIR/../..
DATADIR=/var/lib/uniclient
GRP=uniclient
USR=uniclient

if [ ! -d "$DATADIR" ];then

mkdir $DATADIR;
chgrp $GRP $DATADIR;
chmod 770 $DATADIR; 
echo "created var/lib/uniclient";

fi

echo "not initializing var/lib/uniclient: DIR EXISTS!";
