#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

ROOT=$DIR/../..

NAME=a0-user-group
RC_LINK=$ROOT/etc/rc.d/$NAME;
if ! [ -L "$RC_LINK" ];
 then
 ln -s $ROOT/etc/install.d/$NAME $RC_LINK;
fi

NAME=z8-generate-rc3
RC_LINK=$ROOT/etc/rc.d/$NAME;
if ! [ -L "$RC_LINK" ];
 then
 ln -s $ROOT/etc/install.d/$NAME $RC_LINK;
fi
