#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

ROOT=$DIR/../..

NAME=zz-copy-apache-files

cp $ROOT/etc/apache2/* /etc/apache2/sites-available/;

a2ensite uniclient;
a2ensite auth;
a2ensite auth-server;
a2ensite datacenter;

service apache2 restart;

echo "APACHE CONFIG DONE!";
